# Light or Letdown? — Social Media Analysis of the **Ferrari Luce**
### Web and Social Media Search and Analysis — BSc AI, UniMiB

Self-contained Colab notebook for the Track-1 project (Network + Content + Visualization).
It writes the tested project code (`src/`) into Colab and runs the full pipeline end-to-end,
**including the Reddit scraping** (LAB 1–2).

**Runs with no credentials.** Reddit is scraped live via **Arctic-Shift → PullPush**
(no account, no key); Bluesky is included only if you add an App Password in §2. The full
Reddit pull takes ~10–15 min.

**How to use:** *Runtime → Change runtime type → GPU* (recommended — the transformer models
auto-detect and use it) → **Runtime → Run all**. Pipeline: collect → graph (L3) → communities
(L4) → sentiment/ABSA (L5) → sarcasm/stance/topics/language → NER (L6) → visualization →
download everything. See `MEGAPLAN.md`.

In [1]:
import torch

if torch.cuda.is_available():
    device = torch.device('cuda')
    print(f'GPU: {torch.cuda.get_device_name(0)}')
    print(f'VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')
    torch.cuda.empty_cache()
else:
    device = torch.device('cpu')
    print('No GPU found — running on CPU. Go to Runtime → Change runtime type → GPU.')

print(f'Using device: {device}')

GPU: NVIDIA GeForce RTX 3050 Laptop GPU
VRAM: 4.3 GB
Using device: cuda

## 1. Install dependencies
Colab bundles torch/transformers/pandas/sklearn/networkx/nltk/matplotlib/spaCy. Install the rest.

In [2]:
# Core pipeline deps. Colab already ships torch / transformers / pandas /
# scikit-learn / networkx / nltk / spaCy / matplotlib / seaborn / wordcloud / requests.
# NRCLex needs textblob for its load_raw_text() tokeniser (NRC emotions, LAB 5).
#!pip install -q atproto praw vaderSentiment afinn NRCLex textblob langdetect python-louvain python-dotenv

# BERTopic is an optional extension; if its install fails the pipeline falls
# back automatically to a scikit-learn LDA topic model (no action needed).
#pip install -q bertopic || echo "bertopic not installed -> sklearn LDA fallback will be used"

# spaCy English model for NER (LAB 6)
#!python -m spacy download en_core_web_sm -q
#print("dependencies installed.")

In [3]:
import nltk
for pkg in ("punkt","punkt_tab","stopwords","wordnet","omw-1.4"):
    nltk.download(pkg, quiet=True)
print("NLTK data ready.")

NLTK data ready.

## 2. Credentials — all OPTIONAL (the notebook runs with none)
- **Reddit:** leave blank → collected via **PullPush.io** (no account, no key, no OAuth).
- **Bluesky:** leave blank → Bluesky is **skipped**; to include it, add an *App Password* (bsky.app → Settings → App Passwords).

Nothing is stored. Best practice: use Colab **Secrets** (🔑 in the left sidebar) named `BLUESKY_HANDLE`, `BLUESKY_APP_PASSWORD`, `REDDIT_CLIENT_ID`, `REDDIT_CLIENT_SECRET` — the next cell reads them automatically. Otherwise paste values into the cell. Either way **Runtime → Run all** completes unattended.

In [4]:
import os

# ── Optional credentials ── leave blank to run with NO account ──────────────
# Reddit blank -> PullPush.io (no account).  Bluesky blank -> Bluesky skipped.
# Paste here (kept in memory only) OR, preferably, set them as Colab Secrets.
BLUESKY_HANDLE       = "steffenrizzuto.bsky.social"   # e.g. "you.bsky.social"
BLUESKY_APP_PASSWORD = "rizzuto6"   # App Password, NOT your main password
REDDIT_CLIENT_ID     = ""   # leave blank -> PullPush.io
REDDIT_CLIENT_SECRET = ""   # leave blank -> PullPush.io
REDDIT_USERNAME      = "student"   # only used to build a polite user-agent string

def _resolve(name, pasted):
    """Pasted value > Colab Secret > existing environment variable > ''."""
    if pasted:
        return pasted
    try:
        from google.colab import userdata          # only exists on Colab
        v = userdata.get(name)
        if v:
            return v
    except Exception:
        pass
    return os.environ.get(name, "")

os.environ["BLUESKY_HANDLE"]       = _resolve("BLUESKY_HANDLE", BLUESKY_HANDLE)
os.environ["BLUESKY_APP_PASSWORD"] = _resolve("BLUESKY_APP_PASSWORD", BLUESKY_APP_PASSWORD)
os.environ["REDDIT_CLIENT_ID"]     = _resolve("REDDIT_CLIENT_ID", REDDIT_CLIENT_ID)
os.environ["REDDIT_CLIENT_SECRET"] = _resolve("REDDIT_CLIENT_SECRET", REDDIT_CLIENT_SECRET)
os.environ["REDDIT_USER_AGENT"]    = f"wsa-ferrari-luce/0.1 by u/{REDDIT_USERNAME or 'student'}"

print("Bluesky:", "ON" if os.environ["BLUESKY_HANDLE"] else "skipped (no creds)")
print("Reddit :", "PRAW (API)" if os.environ["REDDIT_CLIENT_ID"] else "PullPush.io (no account)")

Bluesky: ON
Reddit : PullPush.io (no account)

## 3. Project code
This notebook **imports the tested package in `src/`** directly. If you opened the project
folder (uploaded to Colab or mounted from Drive) `src/` is already here; on a bare Colab the
cell below clones the repo to fetch it.

In [5]:
import os, subprocess
# Make the src/ package available. If you're running inside the project folder,
# src/ is already here; otherwise clone the repo to fetch it.
if not os.path.isdir("src"):
    subprocess.run(
        "git clone --depth 1 https://github.com/akirykouski/wsa-ferrari-luce.git _wsa "
        "&& cp -r _wsa/src ./src && cp -r _wsa/report ./report 2>/dev/null",
        shell=True,
    )
if not os.path.isdir("src"):
    raise RuntimeError(
        "src/ not found. The repo is private, so either run this notebook from the "
        "project folder (upload it to Colab or mount Google Drive), or clone a repo "
        "you can access."
    )
for d in ("data/raw", "data/processed", "figures", "report"):
    os.makedirs(d, exist_ok=True)
print("project code ready:", os.path.isdir("src"))

project code ready: True

## 4. Run the pipeline

In [6]:
import pandas as pd
from IPython.display import Image, display
import glob

### 4.1 Collect the data (LAB 1–2)
Scrapes the real data **live**: the official Reddit API if you entered creds in §2,
otherwise **Arctic-Shift → PullPush** (no account, no key). Bluesky is included only if you
supplied an App Password. The full Reddit pull (~370 submissions + their comment trees)
takes **~10–15 min**; re-running fetches fresh posts.

In [7]:
# ── Collect the data (LAB 1-2) ──────────────────────────────────────────
# Live scrape: Reddit API if creds were given in §2, else Arctic-Shift ->
# PullPush (no account). Bluesky only if an App Password was supplied.
from src.collect_bluesky import main as run_bluesky
from src.collect_reddit import main as run_reddit

try:
    run_bluesky()
except Exception as e:
    print("Bluesky collection skipped:", e)

run_reddit()

2026-06-05 15:34:07,900 INFO HTTP Request: POST https://bsky.social/xrpc/com.atproto.server.createSession "HTTP/1.1 200 OK"
2026-06-05 15:34:08,460 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.actor.getProfile?actor=steffenrizzuto.bsky.social "HTTP/1.1 200 OK"
2026-06-05 15:34:08,461 INFO Bluesky login OK as steffenrizzuto.bsky.social
2026-06-05 15:34:08,750 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:09,400 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=25&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:10,033 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=50&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:10,673 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=75&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:11,298 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=100&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:11,932 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=125&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:12,576 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=150&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:13,229 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=175&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:13,860 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=200&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:14,645 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=225&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:15,271 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=250&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:15,904 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=275&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:16,552 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=300&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:17,341 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=325&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:17,965 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=350&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:18,594 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=375&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:19,220 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=400&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:19,857 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=425&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:20,704 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=450&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:21,354 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=475&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:22,010 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=500&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:22,641 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=525&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:23,270 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=550&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:23,897 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=575&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:24,532 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=600&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:25,350 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=625&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:25,976 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=650&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:26,601 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=675&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:27,224 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=700&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:27,855 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=725&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:28,482 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=750&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:29,109 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=775&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:29,740 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=800&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:30,365 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=825&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:30,990 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=850&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:31,621 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=875&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:32,351 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=900&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:32,990 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=925&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:33,617 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=950&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:34,252 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=975&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:35,081 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=1000&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:35,718 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+Luce%22&cursor=1025&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:36,124 INFO   query "Ferrari Luce"               -> 1005 posts
2026-06-05 15:34:36,353 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:37,149 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=25&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:37,799 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=50&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:38,440 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=75&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:39,072 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=100&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:39,700 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=125&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:40,325 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=150&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:40,952 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=175&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:41,662 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=200&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:42,297 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=225&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:42,947 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=250&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:43,571 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=275&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:44,355 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=300&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:45,175 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=325&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:46,104 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=350&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:46,765 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=375&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:47,604 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=400&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:48,239 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=425&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:48,865 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=450&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:49,497 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=475&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:50,129 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=500&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:50,764 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=525&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:51,390 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=550&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:52,016 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=575&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:52,651 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=600&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:53,278 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=625&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:54,063 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=650&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:54,696 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=675&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:55,322 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=700&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:55,954 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=725&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:56,580 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=750&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:57,208 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=775&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:57,836 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=800&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:58,470 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=825&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:59,254 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=850&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:34:59,880 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=875&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:35:00,508 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=900&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:35:01,137 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=925&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:35:01,765 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=950&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:35:02,394 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=975&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:35:03,017 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=1000&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:35:03,737 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=1025&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:35:04,367 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=Ferrari+Luce&cursor=1050&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:35:04,773 INFO   query Ferrari Luce                 -> 1018 posts
2026-06-05 15:35:05,019 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+EV%22&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"
2026-06-05 15:35:05,644 INFO HTTP Request: GET https://stropharia.us-west.host.bsky.network/xrpc/app.bsky.feed.searchPosts?q=%22Ferrari+EV%22&cursor=25&limit=25&since=2025-10-01T00%3A00%3A00Z&sort=latest "HTTP/1.1 200 OK"

### 4.2 Network analysis — graph + centralities (LAB 3), communities (LAB 4)

In [8]:
from src.build_graph import main as run_graph
from src.communities import main as run_comm
run_graph(); run_comm()
print(open("data/processed/graph_summary.txt").read())
print(open("data/processed/communities_summary.txt").read())
display(pd.read_csv("data/processed/nodes_centrality.csv").head(15))

2026-06-05 15:49:16,882 INFO Interaction graph: 8223 nodes, 13792 edges
2026-06-05 15:49:29,631 INFO saved 8223 rows -> C:\Users\stefa\Downloads\wsa-ferrari-luce\data\processed\nodes_centrality.csv
2026-06-05 15:49:30,043 INFO Graph summary:
nodes: 8223
edges: 13792
density: 0.00020
transitivity (clustering): 0.0050
avg clustering: 0.0368
reciprocity: 0.2338
weakly connected components: 125
strongly connected components: 6149
degree assortativity: -0.1590
2026-06-05 15:49:30,614 INFO graph -> C:\Users\stefa\Downloads\wsa-ferrari-luce\data\processed\graph.graphml (open in Gephi)
2026-06-05 15:49:45,427 INFO saved 8223 rows -> C:\Users\stefa\Downloads\wsa-ferrari-luce\data\processed\nodes_communities.csv
2026-06-05 15:49:45,454 INFO Communities:
louvain_n_communities: 165
louvain_modularity: 0.759316090113547
greedy_n_communities: 162
greedy_modularity: 0.7565440468772843
degree_assortativity: -0.22109142643425117
min_community_size: 5
louvain_communities_ge_min: 53

Top members per Louvain community (n>=5; name the camps from these):
  community 6 (n=28): ['thebishf1.bsky.social', 'thetastate.bsky.social', 'd2lo.bsky.social', 'msdianan.bsky.social', 'hrothger4hand.bsky.social', 'lestatdelc.bsky.social', 'arnoldziffel.bsky.social', 'cjwl.bsky.social']
  community 8 (n=9): ['niedermeyer.online', 'peark.es', 'thecrystaljules.bsky.social', 'horadam.bsky.social', 'munson.land', 'manitou202.bsky.social', 'nme365.bsky.social', 'dieterjosef.bsky.social']
  community 10 (n=8): ['dmeance.bsky.social', 'frandroid.com', 'numerama.com', 'automotoofficiel.bsky.social', 'did:plc:wkreszch2k4mumsrlkeaflgn', 'did:plc:hxwo5olhdgcx7bbzu2lewpgo', 'did:plc:godi6h35rjtkw2fd7auxtzct', 'automobile-propre.com']
  community 23 (n=7): ['theverge.com', 'jesspiperfanpage.bsky.social', 'orioncrux.bsky.social', 'ablaze479.bsky.social', 'did:plc:nmrtrhsgos4il6tiiqpq4cm7', 'tomwarren.co.uk', 'bindermichi.bsky.social']
  community 41 (n=5): ['mims.bsky.social', 'ernestb.bsky.social', '5-88t.bsky.social', 'fixitmanaz.bsky.social', 'thejoekelly.bsky.social']
  community 42 (n=7): ['justis4u.bsky.social', 'did:plc:yqsxtfnk4lxbwxtna4pw3lid', 'did:plc:yriarordesrjdj35d4uris74', 'did:plc:uyh5huzxtthtkg6htsgt56lh', 'did:plc:xnlj737ko5wyzkqjq7zjh6im', 'did:plc:et2y4zpyuhp34pr2jc3hbxpe', 'did:plc:uayevtgtbwot25zhocjzb6lv']
  community 68 (n=80): ['Killshot91', 'DrfluffyMD', 'israignatius', 'Dino_Dean', 'SkillPointProblems', 'Far-Resort1936', 'pwhite13', 'TwoPlyDreams']
  community 69 (n=128): ['_fastcompany', 'Recoil42', 'the_joy_of_VI', 'birdseye-maple', 'Blanchimont', 'Adventurous_Oil_6096', 'ggtsu_00', 'Lost-Philosophy-9830']
  community 70 (n=144): ['Blitzen_Bugatti', 'EngineeringMaximum44', 'borgi27', 'ThatMCGuy24', 'msa1124', 'Electronic-Mouse-316', 'chvguitar', 'KalebMorrison1']
  community 71 (n=287): ['Fair_Title2995', 'Murmur1611979', 'NoProfessional4650', 'toastmannn', 'iqisoverrated', 'WTF-UK', 'MagnumBigPI', 'divinitylost94']
  community 72 (n=137): ['chri99_', 'Tellittomy6pac', 'jlgolson', 'eggwhitecocktails', 'Gustafa7', 'gaukmotors', 'Mission_Sympathy_915', 'pekebooo']
  community 73 (n=270): ['abdunbunbun', 'Great-Technician-415', 'Open-Lingonberry1357', 'Galencourt-Lover', 'uselessgenius69', 'shadow_sniper67', 'CarYenta', 'DreadedFate7']
  community 74 (n=144): ['voxpopper', 'Difficult_Jaguar_578', 'drughi_', 'Signal_Quarter_74', 'oursrequin', 'Severe-Break-3935', 'gingerbeard1321', 'reaper7319']
  community 75 (n=126): ['andix3', 'lolyeahsure', 'HatsuneM1ku', 'TheSeaShadow', 'Tifoso89', 'shyataroo', 'randompersonx', 'rainydevil7']
  community 76 (n=282): ['Mac-Tyson', 'Temporary_Kick2089', 'Lonely_Refuse4988', 'ZobeidZuma', 'Noderly', 'savageotter', 'ZeroWashu', 'br0wntree']
  community 77 (n=188): ['kkhouete', 'ProtoplanetaryNebula', 'ScipioAfricanusMAJ', 'shy247er', 'Funny_Energy5240', 'humbleObserver', 'IndependenceIcy9626', 'NckyDC']
  community 78 (n=210): ['emptybottle2405', 'LocalBasketCase991-2', 'opbmedia', 'JaakOfTheDirt', 'AriaDio', 'Novel_Land9320', 'wybird', 'Vincoppredd']
  community 79 (n=31): ['Practical_Back_6795', 'Funny_Procedure_7609', 'AppropriatePiglet581', 'Comfortable_Sugar_67', 'thejetssuckbigtime', 'Thisatrick', 'Nine_block', 'RandomAccessMemoriez']
  community 80 (n=39): ['Arvosss', 'Puzzled_Elephant_190', 'oldmonk_97', 'IBets', 'Arhigos', 'Daftworks', 'RUSuper', 'omerkawaii']
  community 82 (n=181): ['NyckDebreeze', 'Frosty_Resource7740', 'joyridechamp', 'gregelectric', 'aiden2002', 'mehdotdotdotdot', '-Feisty-Preference-', 'FonkyFong']
  community 84 (n=250): ['DanGleeballs', 'surrogate_uprising', 'Gr33nym8', 'TheModeratorWrangler', 'Consistent-Annual268', 'Normal-Information57', '0621Hertz', 'Lonely-Entry-7206']
  community 85 (n=121): ['Saurta17', 'SHARPxSHOOTER', 'NikiUhoto', 'gitty7456', 'ssvladi', 'FZwertyu34', 'digsterin0', 'faithOver']
  community 86 (n=364): ['ProxyLumina', 'BrienneOfFuckinTarth', 'Important-Rest-7302', 'Totallynormalname_', 'newtrilobite', 'rutgers-cs334', 'crashedsnow', 'anonduplo']
  community 87 (n=256): ['NegotiationNew9264', 'Mean-Reference-6104', 'Professional-Heat894', 'stillusesAOL', 'Zestyclose_Ad2429', 'Recidive', 'Kalmer1', 'Pure-Sir-5064']
  community 88 (n=360): ['DeonEVE', 'uselessthrowaway5050', 'robottyno', 'noahscanlon', 'Emotional_Two_8059', 'B5HARMONY', 'AcrobaticButterfly', 'Fidget11']
  community 94 (n=265): ['k_entity', 'bojacker', 'Skybully27', 'ImageRevolutionary43', 'Crazy-Commission-461', 'Pure_Tradition3761', 'Outrageous-Stop4366', 'lasiru']
  community 95 (n=252): ['FoxHound6112', 'AKN21x', 'dsarif70', 'Godvater', 'TheLewJD', 'Dazzling-Quarter-490', 'edchikel1', '0xe1e10d68']
  community 96 (n=37): ['Powerful-Ostrich-120', 'KarmaticEvolution', 'BarberNo9798', 'jzach1983', 'vanderohe', 'dgdfthr', 'Doom_Cat', 'lorddouche414']
  community 97 (n=534): ['strongmanass', 'freezies1234', 'Silentkindfromsauna', 'hi_im_bored13', 'threeinacorner', 'Slice5755', 'nukleabomb', 'narwhal_breeder']
  community 98 (n=41): ['mountaineer', '25inbone', 'ItsGizzman', 'J_NonServiam', 'Ok_Two_2604', 'boat_hamster', 'Tarmacked', 'bwoah_gimmethedrink']
  community 99 (n=244): ['LongjumpingLock5875', 'cy_88', 'prisongovernor', 'crshbndct', 'Thomas_633_Mk2', 'cannedrex2406', 'stupidber', 'm4a785m']
  community 100 (n=159): ['W9967', 'generalright', 'hutacars', 'wtfduud', 'RIP_Soulja_Slim', 'AndreLeGeant88', 'PRSArchon', 'twothoutwo']
  community 104 (n=179): ['Anchor_Aways', 'Uptons_BJs', 'Lower_Kick268', 'Fun_Success_3283', 'ASource3511', 'Eaglerulez2', 'Nounoon', 'DisastrousMaximum464']
  community 106 (n=5): ['opeth10657', 'AlphaTravel', 'T-Baaller', 'Vesuvias', 'Lawineer']
  community 113 (n=196): ['Heckmotorist', 'DanielG165', 'KingMario05', 'idkbruh653', 'Iridium-Silver', 'JK_Chan', 'Bonerchill', 'willpc14']
  community 127 (n=199): ['just_dave', 'daBomb26', 'Santa_Ricotta69', 'James_Vowles', 'trail-g62Bim', 'FourEyesAndThighs', 'time_to_reset', 'Dachshand']
  community 128 (n=173): ['cookingboy', 'Ill-Panic-4533', 'Steeviie', 'AnonymousEngineer_', 'scaled2913', 'krackenracer', 'mike_litoris18', 'VitoXzX']
  community 129 (n=386): ['linknewtab', 'Lopsided_Quarter_931', 'TripleShotPls', '-Stoic-', 'gloriousinquisitor', 'Logitech4873', 'TemuPacemaker', 'howyinzdoingnat']
  community 131 (n=308): ['mightyopik', 'nemandzax', 'wannacumnbeatmeoff', 'enigmaunbound', 'Acceptable_Visit_115', 'stevedapp', 'fitm3', 'goonmaster678941']
  community 132 (n=6): ['boutell', 'Loading1984', 'Mammoth-Barber-8541', 'killerrin', 'TraditionalClick992', 'sctbke']
  community 133 (n=292): ['xABuHaMeDx', 'anthn885', 'banana_bubbles', 'ThatsABingoJa', 'Inflammabull', 'acog', 'AKiss20', 'Fire_Otter']
  community 134 (n=187): ['outremer_empire', 'The3rdbaboon', 'budgefrankly', 'FlipReset4Fun', 'uusrikas', 'jedifolklore', 'ElegantBiscuit', 'GrumpyMcPedant']
  community 135 (n=90): ['Effective_Moose_4997', 'banned20', 'AskMantis23', 'TheGamingFennec', 'OscarMyk', 'TheLoneEcho', 'Late-Button-6559', 'riyosz']
  community 136 (n=104): ['dimka1307', 'n05h', 'MissionLet7301', 'ScroochDown', 'Projectfluid', 'Its_Xavier_Henry', 'TheClarendons', 'ThePursuitist']
  community 137 (n=6): ['IdolizeHamsters', '43JoJo', 'FlashFox24', 'rob_s_458', 'United_Engine_5719', 'CoolEnergy581']
  community 143 (n=96): ['PiggySVW', 'IamMrEric', 'LegendRazgriz', 'cryptoneedstodie', 'denbommer', 'very_moist_raccoon', 'sthegreT', 'No_Cherry_1423']
  community 145 (n=78): ['NoRefunds2021', 'ThisToe9628', 'No-Surprise9411', 'reddit0r_123', 'scarnegie96', 'femboyisbestboy', 'ur_internet_dad', 'Keanu990321']
  community 150 (n=11): ['Lyndon_Boner_Johnson', 'DardanGameDev', 'DijuridoosDesert', 'psdpro7', 'BobSacamano47', 'rym1469', 'RealJyrone', 'Scedasticity1']
  community 154 (n=5): ['Brokettman', 'guilcol', 'ExultantSandwich', 'amputeenager', 'Royal_Airport7940']
  community 157 (n=78): ['MeloniousV2', 'jhonkas', 'Dreams-Visions', 'oandakid718', 'sickmemes48', 'Ihateporn2020', 'Cheetah_05', 'Unusual_Currency_294']
  community 160 (n=324): ['Public-Promotion-744', 'callsonreddit', 'SheBenOnMyJohnson', 'floo82', 'Dependent_Garden6168', 'HOI4_Loser', 'Paykuh-', 'Ok-Calendar-4130']
  community 162 (n=5): ['Locke_____Lamora', 'KingOfWhateverr', 'roughedged', 'Real_Attempt_6889', 'TomatoSpecialist6879']
  community 164 (n=46): ['alfred250', 'Rich-Use1484', 'Buddah_Chillz420', 'penifSMASH', 'gghomhom', 'kaapooj', 'zedk47', 'No-Resource9879']
  other (merged communities with n<5): 255 accounts

nodes: 8223
edges: 13792
density: 0.00020
transitivity (clustering): 0.0050
avg clustering: 0.0368
reciprocity: 0.2338
weakly connected components: 125
strongly connected components: 6149
degree assortativity: -0.1590
louvain_n_communities: 165
louvain_modularity: 0.759316090113547
greedy_n_communities: 162
greedy_modularity: 0.7565440468772843
degree_assortativity: -0.22109142643425117
min_community_size: 5
louvain_communities_ge_min: 53

Top members per Louvain community (n>=5; name the camps from these):
  community 6 (n=28): ['thebishf1.bsky.social', 'thetastate.bsky.social', 'd2lo.bsky.social', 'msdianan.bsky.social', 'hrothger4hand.bsky.social', 'lestatdelc.bsky.social', 'arnoldziffel.bsky.social', 'cjwl.bsky.social']
  community 8 (n=9): ['niedermeyer.online', 'peark.es', 'thecrystaljules.bsky.social', 'horadam.bsky.social', 'munson.land', 'manitou202.bsky.social', 'nme365.bsky.social', 'dieterjosef.bsky.social']
  community 10 (n=8): ['dmeance.bsky.social', 'frandroid.com', 'numerama.com', 'automotoofficiel.bsky.social', 'did:plc:wkreszch2k4mumsrlkeaflgn', 'did:plc:hxwo5olhdgcx7bbzu2lewpgo', 'did:plc:godi6h35rjtkw2fd7auxtzct', 'automobile-propre.com']
  community 23 (n=7): ['theverge.com', 'jesspiperfanpage.bsky.social', 'orioncrux.bsky.social', 'ablaze479.bsky.social', 'did:plc:nmrtrhsgos4il6tiiqpq4cm7', 'tomwarren.co.uk', 'bindermichi.bsky.social']
  community 41 (n=5): ['mims.bsky.social', 'ernestb.bsky.social', '5-88t.bsky.social', 'fixitmanaz.bsky.social', 'thejoekelly.bsky.social']
  community 42 (n=7): ['justis4u.bsky.social', 'did:plc:yqsxtfnk4lxbwxtna4pw3lid', 'did:plc:yriarordesrjdj35d4uris74', 'did:plc:uyh5huzxtthtkg6htsgt56lh', 'did:plc:xnlj737ko5wyzkqjq7zjh6im', 'did:plc:et2y4zpyuhp34pr2jc3hbxpe', 'did:plc:uayevtgtbwot25zhocjzb6lv']
  community 68 (n=80): ['Killshot91', 'DrfluffyMD', 'israignatius', 'Dino_Dean', 'SkillPointProblems', 'Far-Resort1936', 'pwhite13', 'TwoPlyDreams']
  community 69 (n=128): ['_fastcompany', 'Recoil42', 'the_joy_of_VI', 'birdseye-maple', 'Blanchimont', 'Adventurous_Oil_6096', 'ggtsu_00', 'Lost-Philosophy-9830']
  community 70 (n=144): ['Blitzen_Bugatti', 'EngineeringMaximum44', 'borgi27', 'ThatMCGuy24', 'msa1124', 'Electronic-Mouse-316', 'chvguitar', 'KalebMorrison1']
  community 71 (n=287): ['Fair_Title2995', 'Murmur1611979', 'NoProfessional4650', 'toastmannn', 'iqisoverrated', 'WTF-UK', 'MagnumBigPI', 'divinitylost94']
  community 72 (n=137): ['chri99_', 'Tellittomy6pac', 'jlgolson', 'eggwhitecocktails', 'Gustafa7', 'gaukmotors', 'Mission_Sympathy_915', 'pekebooo']
  community 73 (n=270): ['abdunbunbun', 'Great-Technician-415', 'Open-Lingonberry1357', 'Galencourt-Lover', 'uselessgenius69', 'shadow_sniper67', 'CarYenta', 'DreadedFate7']
  community 74 (n=144): ['voxpopper', 'Difficult_Jaguar_578', 'drughi_', 'Signal_Quarter_74', 'oursrequin', 'Severe-Break-3935', 'gingerbeard1321', 'reaper7319']
  community 75 (n=126): ['andix3', 'lolyeahsure', 'HatsuneM1ku', 'TheSeaShadow', 'Tifoso89', 'shyataroo', 'randompersonx', 'rainydevil7']
  community 76 (n=282): ['Mac-Tyson', 'Temporary_Kick2089', 'Lonely_Refuse4988', 'ZobeidZuma', 'Noderly', 'savageotter', 'ZeroWashu', 'br0wntree']
  community 77 (n=188): ['kkhouete', 'ProtoplanetaryNebula', 'ScipioAfricanusMAJ', 'shy247er', 'Funny_Energy5240', 'humbleObserver', 'IndependenceIcy9626', 'NckyDC']
  community 78 (n=210): ['emptybottle2405', 'LocalBasketCase991-2', 'opbmedia', 'JaakOfTheDirt', 'AriaDio', 'Novel_Land9320', 'wybird', 'Vincoppredd']
  community 79 (n=31): ['Practical_Back_6795', 'Funny_Procedure_7609', 'AppropriatePiglet581', 'Comfortable_Sugar_67', 'thejetssuckbigtime', 'Thisatrick', 'Nine_block', 'RandomAccessMemoriez']
  community 80 (n=39): ['Arvosss', 'Puzzled_Elephant_190', 'oldmonk_97', 'IBets', 'Arhigos', 'Daftworks', 'RUSuper', 'omerkawaii']
  community 82 (n=181): ['NyckDebreeze', 'Frosty_Resource7740', 'joyridechamp', 'gregelectric', 'aiden2002', 'mehdotdotdotdot', '-Feisty-Preference-', 'FonkyFong']
  community 84 (n=250): ['DanGleeballs', 'surrogate_uprising', 'Gr33nym8', 'TheModeratorWrangler', 'Consistent-Annual268', 'Normal-Information57', '0621Hertz', 'Lonely-Entry-7206']
  community 85 (n=121): ['Saurta17', 'SHARPxSHOOTER', 'NikiUhoto', 'gitty7456', 'ssvladi', 'FZwertyu34', 'digsterin0', 'faithOver']
  community 86 (n=364): ['ProxyLumina', 'BrienneOfFuckinTarth', 'Important-Rest-7302', 'Totallynormalname_', 'newtrilobite', 'rutgers-cs334', 'crashedsnow', 'anonduplo']
  community 87 (n=256): ['NegotiationNew9264', 'Mean-Reference-6104', 'Professional-Heat894', 'stillusesAOL', 'Zestyclose_Ad2429', 'Recidive', 'Kalmer1', 'Pure-Sir-5064']
  community 88 (n=360): ['DeonEVE', 'uselessthrowaway5050', 'robottyno', 'noahscanlon', 'Emotional_Two_8059', 'B5HARMONY', 'AcrobaticButterfly', 'Fidget11']
  community 94 (n=265): ['k_entity', 'bojacker', 'Skybully27', 'ImageRevolutionary43', 'Crazy-Commission-461', 'Pure_Tradition3761', 'Outrageous-Stop4366', 'lasiru']
  community 95 (n=252): ['FoxHound6112', 'AKN21x', 'dsarif70', 'Godvater', 'TheLewJD', 'Dazzling-Quarter-490', 'edchikel1', '0xe1e10d68']
  community 96 (n=37): ['Powerful-Ostrich-120', 'KarmaticEvolution', 'BarberNo9798', 'jzach1983', 'vanderohe', 'dgdfthr', 'Doom_Cat', 'lorddouche414']
  community 97 (n=534): ['strongmanass', 'freezies1234', 'Silentkindfromsauna', 'hi_im_bored13', 'threeinacorner', 'Slice5755', 'nukleabomb', 'narwhal_breeder']
  community 98 (n=41): ['mountaineer', '25inbone', 'ItsGizzman', 'J_NonServiam', 'Ok_Two_2604', 'boat_hamster', 'Tarmacked', 'bwoah_gimmethedrink']
  community 99 (n=244): ['LongjumpingLock5875', 'cy_88', 'prisongovernor', 'crshbndct', 'Thomas_633_Mk2', 'cannedrex2406', 'stupidber', 'm4a785m']
  community 100 (n=159): ['W9967', 'generalright', 'hutacars', 'wtfduud', 'RIP_Soulja_Slim', 'AndreLeGeant88', 'PRSArchon', 'twothoutwo']
  community 104 (n=179): ['Anchor_Aways', 'Uptons_BJs', 'Lower_Kick268', 'Fun_Success_3283', 'ASource3511', 'Eaglerulez2', 'Nounoon', 'DisastrousMaximum464']
  community 106 (n=5): ['opeth10657', 'AlphaTravel', 'T-Baaller', 'Vesuvias', 'Lawineer']
  community 113 (n=196): ['Heckmotorist', 'DanielG165', 'KingMario05', 'idkbruh653', 'Iridium-Silver', 'JK_Chan', 'Bonerchill', 'willpc14']
  community 127 (n=199): ['just_dave', 'daBomb26', 'Santa_Ricotta69', 'James_Vowles', 'trail-g62Bim', 'FourEyesAndThighs', 'time_to_reset', 'Dachshand']
  community 128 (n=173): ['cookingboy', 'Ill-Panic-4533', 'Steeviie', 'AnonymousEngineer_', 'scaled2913', 'krackenracer', 'mike_litoris18', 'VitoXzX']
  community 129 (n=386): ['linknewtab', 'Lopsided_Quarter_931', 'TripleShotPls', '-Stoic-', 'gloriousinquisitor', 'Logitech4873', 'TemuPacemaker', 'howyinzdoingnat']
  community 131 (n=308): ['mightyopik', 'nemandzax', 'wannacumnbeatmeoff', 'enigmaunbound', 'Acceptable_Visit_115', 'stevedapp', 'fitm3', 'goonmaster678941']
  community 132 (n=6): ['boutell', 'Loading1984', 'Mammoth-Barber-8541', 'killerrin', 'TraditionalClick992', 'sctbke']
  community 133 (n=292): ['xABuHaMeDx', 'anthn885', 'banana_bubbles', 'ThatsABingoJa', 'Inflammabull', 'acog', 'AKiss20', 'Fire_Otter']
  community 134 (n=187): ['outremer_empire', 'The3rdbaboon', 'budgefrankly', 'FlipReset4Fun', 'uusrikas', 'jedifolklore', 'ElegantBiscuit', 'GrumpyMcPedant']
  community 135 (n=90): ['Effective_Moose_4997', 'banned20', 'AskMantis23', 'TheGamingFennec', 'OscarMyk', 'TheLoneEcho', 'Late-Button-6559', 'riyosz']
  community 136 (n=104): ['dimka1307', 'n05h', 'MissionLet7301', 'ScroochDown', 'Projectfluid', 'Its_Xavier_Henry', 'TheClarendons', 'ThePursuitist']
  community 137 (n=6): ['IdolizeHamsters', '43JoJo', 'FlashFox24', 'rob_s_458', 'United_Engine_5719', 'CoolEnergy581']
  community 143 (n=96): ['PiggySVW', 'IamMrEric', 'LegendRazgriz', 'cryptoneedstodie', 'denbommer', 'very_moist_raccoon', 'sthegreT', 'No_Cherry_1423']
  community 145 (n=78): ['NoRefunds2021', 'ThisToe9628', 'No-Surprise9411', 'reddit0r_123', 'scarnegie96', 'femboyisbestboy', 'ur_internet_dad', 'Keanu990321']
  community 150 (n=11): ['Lyndon_Boner_Johnson', 'DardanGameDev', 'DijuridoosDesert', 'psdpro7', 'BobSacamano47', 'rym1469', 'RealJyrone', 'Scedasticity1']
  community 154 (n=5): ['Brokettman', 'guilcol', 'ExultantSandwich', 'amputeenager', 'Royal_Airport7940']
  community 157 (n=78): ['MeloniousV2', 'jhonkas', 'Dreams-Visions', 'oandakid718', 'sickmemes48', 'Ihateporn2020', 'Cheetah_05', 'Unusual_Currency_294']
  community 160 (n=324): ['Public-Promotion-744', 'callsonreddit', 'SheBenOnMyJohnson', 'floo82', 'Dependent_Garden6168', 'HOI4_Loser', 'Paykuh-', 'Ok-Calendar-4130']
  community 162 (n=5): ['Locke_____Lamora', 'KingOfWhateverr', 'roughedged', 'Real_Attempt_6889', 'TomatoSpecialist6879']
  community 164 (n=46): ['alfred250', 'Rich-Use1484', 'Buddah_Chillz420', 'penifSMASH', 'gghomhom', 'kaapooj', 'zedk47', 'No-Resource9879']
  other (merged communities with n<5): 255 accounts

,node,platform,in_degree,out_degree,in_degree_centrality,out_degree_centrality,betweenness,closeness,pagerank,eigenvector
0,Public-Promotion-744,reddit,259,17,0.031501,0.002068,0.007764,0.084766,0.025062,NaN
1,k_entity,reddit,260,0,0.031622,0.000000,0.000000,0.154024,0.012820,NaN
2,NegotiationNew9264,reddit,305,6,0.037096,0.000730,0.011763,0.121039,0.011888,NaN
3,Mac-Tyson,reddit,252,12,0.030649,0.001459,0.017541,0.140776,0.011761,NaN
4,DeonEVE,reddit,363,0,0.044150,0.000000,0.000000,0.152122,0.010084,NaN
5,mightyopik,reddit,142,12,0.017271,0.001459,0.009722,0.125083,0.009846,NaN
6,Slice5755,reddit,38,7,0.004622,0.000851,0.004188,0.127022,0.008940,NaN
7,Fair_Title2995,reddit,173,81,0.021041,0.009852,0.059754,0.134763,0.007267,NaN
8,FoxHound6112,reddit,256,1,0.031136,0.000122,0.000012,0.132880,0.006279,NaN
9,Effective_Moose_4997,reddit,64,20,0.007784,0.002432,0.004221,0.077673,0.006209,NaN
10,NyckDebreeze,reddit,196,0,0.023838,0.000000,0.000000,0.133889,0.004917,NaN
11,ProxyLumina,reddit,76,41,0.009243,0.004987,0.009460,0.119113,0.004911,NaN
12,MeloniousV2,reddit,51,26,0.006203,0.003162,0.004111,0.092875,0.004676,NaN
13,Blitzen_Bugatti,reddit,117,5,0.014230,0.000608,0.004960,0.108018,0.004640,NaN
14,NoRefunds2021,reddit,37,2,0.004500,0.000243,0.000313,0.088442,0.004514,NaN

### 4.3 Content — sentiment/emotion/ABSA (LAB 5) + enrichments (sarcasm RQ6, stance RQ7, topics, language RQ8)

In [9]:
from src.content_sentiment import main as run_sent
from src.content_enrich import main as run_enrich
run_sent(); run_enrich()
display(pd.read_csv("data/processed/aspect_sentiment.csv"))
display(pd.read_csv("data/processed/language_sentiment.csv"))

2026-06-05 15:49:45,904 INFO dropped 300 bot-authored documents
2026-06-05 15:50:35,282 INFO Corpus: 19680 documents ({'reddit': 16992, 'bluesky': 2688})
2026-06-05 15:50:55,397 INFO NRC emotions: 12134/19680 docs matched the lexicon
c:\Users\stefa\Downloads\wsa-ferrari-luce\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2026-06-05 15:51:05,145 INFO HTTP Request: HEAD https://huggingface.co/cardiffnlp/twitter-roberta-base-sentiment-latest/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-06-05 15:51:05,158 INFO HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/cardiffnlp/twitter-roberta-base-sentiment-latest/3216a57f2a0d9c45a2e6c20157c20c49fb4bf9c7/config.json "HTTP/1.1 200 OK"
2026-06-05 15:51:05,310 INFO HTTP Request: HEAD https://huggingface.co/cardiffnlp/twitter-roberta-base-sentiment-latest/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
2026-06-05 15:51:05,440 INFO HTTP Request: GET https://huggingface.co/api/models/cardiffnlp/twitter-roberta-base-sentiment-latest "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 201/201 [00:00<00:00, 22817.34it/s]
[transformers] RobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-roberta-base-sentiment-latest
Key                         | Status     |  |
----------------------------+------------+--+-
roberta.pooler.dense.weight | UNEXPECTED |  |
roberta.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-06-05 15:51:05,574 INFO HTTP Request: GET https://huggingface.co/api/models/cardiffnlp/twitter-roberta-base-sentiment-latest/commits/main "HTTP/1.1 200 OK"
2026-06-05 15:51:05,659 INFO HTTP Request: GET https://huggingface.co/api/models/cardiffnlp/twitter-roberta-base-sentiment-latest/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-06-05 15:51:05,731 INFO HTTP Request: GET https://huggingface.co/api/models/cardiffnlp/twitter-roberta-base-sentiment-latest/discussions?p=0 "HTTP/1.1 200 OK"
2026-06-05 15:51:05,783 INFO HTTP Request: GET https://huggingface.co/api/models/cardiffnlp/twitter-roberta-base-sentiment-latest/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-06-05 15:51:05,876 INFO HTTP Request: GET https://huggingface.co/api/models/cardiffnlp/twitter-roberta-base-sentiment-latest/commits/refs%2Fpr%2F43 "HTTP/1.1 200 OK"
2026-06-05 15:51:05,998 INFO HTTP Request: HEAD https://huggingface.co/cardiffnlp/twitter-roberta-base-sentiment-latest/resolve/refs%2Fpr%2F43/model.safetensors.index.json "HTTP/1.1 404 Not Found"
2026-06-05 15:51:06,121 INFO HTTP Request: HEAD https://huggingface.co/cardiffnlp/twitter-roberta-base-sentiment-latest/resolve/refs%2Fpr%2F43/model.safetensors "HTTP/1.1 302 Found"
2026-06-05 15:51:07,154 INFO pipeline 'sentiment-analysis' (cardiffnlp/twitter-roberta-base-sentiment-latest) on GPU
2026-06-05 15:51:08,360 INFO   transformer sentiment 0/19680
[transformers] You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
2026-06-05 15:51:12,273 INFO   transformer sentiment 320/19680
2026-06-05 15:51:16,246 INFO   transformer sentiment 640/19680
2026-06-05 15:51:20,116 INFO   transformer sentiment 960/19680
2026-06-05 15:51:24,171 INFO   transformer sentiment 1280/19680
2026-06-05 15:51:28,019 INFO   transformer sentiment 1600/19680
2026-06-05 15:51:31,850 INFO   transformer sentiment 1920/19680
2026-06-05 15:51:35,823 INFO   transformer sentiment 2240/19680
2026-06-05 15:51:39,901 INFO   transformer sentiment 2560/19680
2026-06-05 15:51:44,791 INFO   transformer sentiment 2880/19680
2026-06-05 15:51:49,699 INFO   transformer sentiment 3200/19680
2026-06-05 15:51:53,686 INFO   transformer sentiment 3520/19680
2026-06-05 15:51:58,104 INFO   transformer sentiment 3840/19680
2026-06-05 15:52:02,494 INFO   transformer sentiment 4160/19680
2026-06-05 15:52:06,837 INFO   transformer sentiment 4480/19680
2026-06-05 15:52:11,069 INFO   transformer sentiment 4800/19680
2026-06-05 15:52:15,192 INFO   transformer sentiment 5120/19680
2026-06-05 15:52:19,477 INFO   transformer sentiment 5440/19680
2026-06-05 15:52:23,529 INFO   transformer sentiment 5760/19680
2026-06-05 15:52:27,832 INFO   transformer sentiment 6080/19680
2026-06-05 15:52:32,008 INFO   transformer sentiment 6400/19680
2026-06-05 15:52:36,008 INFO   transformer sentiment 6720/19680
2026-06-05 15:52:40,161 INFO   transformer sentiment 7040/19680
2026-06-05 15:52:44,184 INFO   transformer sentiment 7360/19680
2026-06-05 15:52:48,157 INFO   transformer sentiment 7680/19680
2026-06-05 15:52:52,182 INFO   transformer sentiment 8000/19680
2026-06-05 15:52:56,093 INFO   transformer sentiment 8320/19680
2026-06-05 15:53:00,161 INFO   transformer sentiment 8640/19680
2026-06-05 15:53:04,299 INFO   transformer sentiment 8960/19680
2026-06-05 15:53:08,351 INFO   transformer sentiment 9280/19680
2026-06-05 15:53:12,572 INFO   transformer sentiment 9600/19680
2026-06-05 15:53:16,609 INFO   transformer sentiment 9920/19680
2026-06-05 15:53:20,633 INFO   transformer sentiment 10240/19680
2026-06-05 15:53:24,738 INFO   transformer sentiment 10560/19680
2026-06-05 15:53:28,732 INFO   transformer sentiment 10880/19680
2026-06-05 15:53:33,305 INFO   transformer sentiment 11200/19680
2026-06-05 15:53:38,930 INFO   transformer sentiment 11520/19680
2026-06-05 15:53:44,529 INFO   transformer sentiment 11840/19680
2026-06-05 15:53:50,103 INFO   transformer sentiment 12160/19680
2026-06-05 15:53:55,922 INFO   transformer sentiment 12480/19680
2026-06-05 15:54:01,992 INFO   transformer sentiment 12800/19680
2026-06-05 15:54:06,294 INFO   transformer sentiment 13120/19680
2026-06-05 15:54:10,825 INFO   transformer sentiment 13440/19680
2026-06-05 15:54:14,927 INFO   transformer sentiment 13760/19680
2026-06-05 15:54:19,084 INFO   transformer sentiment 14080/19680
2026-06-05 15:54:23,327 INFO   transformer sentiment 14400/19680
2026-06-05 15:54:28,743 INFO   transformer sentiment 14720/19680
2026-06-05 15:54:33,256 INFO   transformer sentiment 15040/19680
2026-06-05 15:54:37,622 INFO   transformer sentiment 15360/19680
2026-06-05 15:54:43,199 INFO   transformer sentiment 15680/19680
2026-06-05 15:54:48,209 INFO   transformer sentiment 16000/19680
2026-06-05 15:54:53,587 INFO   transformer sentiment 16320/19680
2026-06-05 15:54:58,533 INFO   transformer sentiment 16640/19680
2026-06-05 15:55:03,331 INFO   transformer sentiment 16960/19680
2026-06-05 15:55:09,903 INFO   transformer sentiment 17280/19680
2026-06-05 15:55:14,776 INFO   transformer sentiment 17600/19680
2026-06-05 15:55:19,402 INFO   transformer sentiment 17920/19680
2026-06-05 15:55:24,183 INFO   transformer sentiment 18240/19680
2026-06-05 15:55:29,160 INFO   transformer sentiment 18560/19680
2026-06-05 15:55:33,977 INFO   transformer sentiment 18880/19680
2026-06-05 15:55:39,066 INFO   transformer sentiment 19200/19680
2026-06-05 15:55:44,299 INFO   transformer sentiment 19520/19680
2026-06-05 15:55:46,799 INFO saved 19680 rows -> C:\Users\stefa\Downloads\wsa-ferrari-luce\data\processed\documents_sentiment.csv
2026-06-05 15:55:47,359 INFO saved 9 rows -> C:\Users\stefa\Downloads\wsa-ferrari-luce\data\processed\aspect_sentiment.csv
2026-06-05 15:55:47,402 INFO saved 246 rows -> C:\Users\stefa\Downloads\wsa-ferrari-luce\data\processed\sentiment_timeline.csv
2026-06-05 15:55:47,407 INFO Sentiment label distribution:
transformer_label
neutral     8842
negative    7462
positive    3376
2026-06-05 15:55:47,783 INFO Loaded sentiment-scored corpus (19680 docs).
2026-06-05 15:55:47,934 INFO HTTP Request: HEAD https://huggingface.co/cardiffnlp/twitter-roberta-base-irony/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-06-05 15:55:47,935 WARNING Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-06-05 15:55:47,945 INFO HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/cardiffnlp/twitter-roberta-base-irony/3bf8f118bdf6b00c99658151ef10c9a0b9afd6bf/config.json "HTTP/1.1 200 OK"
2026-06-05 15:55:48,077 INFO HTTP Request: HEAD https://huggingface.co/cardiffnlp/twitter-roberta-base-irony/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
2026-06-05 15:55:48,200 INFO HTTP Request: GET https://huggingface.co/api/models/cardiffnlp/twitter-roberta-base-irony "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 201/201 [00:00<00:00, 17468.30it/s]
2026-06-05 15:55:48,342 INFO HTTP Request: GET https://huggingface.co/api/models/cardiffnlp/twitter-roberta-base-irony/commits/main "HTTP/1.1 200 OK"
2026-06-05 15:55:48,401 INFO HTTP Request: GET https://huggingface.co/api/models/cardiffnlp/twitter-roberta-base-irony/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-06-05 15:55:48,473 INFO HTTP Request: GET https://huggingface.co/api/models/cardiffnlp/twitter-roberta-base-irony/discussions?p=0 "HTTP/1.1 200 OK"
2026-06-05 15:55:48,526 INFO HTTP Request: GET https://huggingface.co/api/models/cardiffnlp/twitter-roberta-base-irony/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-06-05 15:55:48,656 INFO HTTP Request: GET https://huggingface.co/api/models/cardiffnlp/twitter-roberta-base-irony/commits/refs%2Fpr%2F3 "HTTP/1.1 200 OK"
2026-06-05 15:55:48,797 INFO HTTP Request: HEAD https://huggingface.co/cardiffnlp/twitter-roberta-base-irony/resolve/refs%2Fpr%2F3/model.safetensors.index.json "HTTP/1.1 404 Not Found"
2026-06-05 15:55:48,922 INFO HTTP Request: HEAD https://huggingface.co/cardiffnlp/twitter-roberta-base-irony/resolve/refs%2Fpr%2F3/model.safetensors "HTTP/1.1 302 Found"
2026-06-05 15:55:50,262 INFO pipeline 'text-classification' (cardiffnlp/twitter-roberta-base-irony) on GPU
2026-06-05 16:00:27,300 INFO Irony prevalence: 19.5%
2026-06-05 16:00:27,548 INFO HTTP Request: HEAD https://huggingface.co/facebook/bart-large-mnli/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-06-05 16:00:27,559 INFO HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/facebook/bart-large-mnli/d7645e127eaf1aefc7862fd59a17a5aa8558b8ce/config.json "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 515/515 [00:00<00:00, 2765.27it/s]
2026-06-05 16:00:28,122 INFO HTTP Request: GET https://huggingface.co/api/models/facebook/bart-large-mnli/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-06-05 16:00:28,245 INFO HTTP Request: GET https://huggingface.co/api/models/facebook/bart-large-mnli/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-06-05 16:00:33,149 INFO pipeline 'zero-shot-classification' (facebook/bart-large-mnli) on GPU
2026-06-05 16:00:33,151 WARNING stance capped at 2000/19680 docs for runtime.
2026-06-05 16:04:37,671 INFO stance(luce): {'against': 1046, 'favor': 870, 'neutral': 84}
2026-06-05 16:08:29,438 INFO stance(ev_transition): {'favor': 1031, 'against': 819, 'neutral': 150}
2026-06-05 16:08:45,635 INFO No device provided, using cuda:0
2026-06-05 16:08:45,791 INFO HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-06-05 16:08:45,801 INFO HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/modules.json "HTTP/1.1 200 OK"
2026-06-05 16:08:45,929 INFO HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-06-05 16:08:45,940 INFO HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-06-05 16:08:45,945 INFO Loading SentenceTransformer model from sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2.
2026-06-05 16:08:46,068 INFO HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-06-05 16:08:46,078 INFO HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-06-05 16:08:46,202 INFO HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-06-05 16:08:46,211 INFO HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/README.md "HTTP/1.1 200 OK"
2026-06-05 16:08:46,335 INFO HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-06-05 16:08:46,345 INFO HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/modules.json "HTTP/1.1 200 OK"
2026-06-05 16:08:46,468 INFO HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-06-05 16:08:46,478 INFO HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-06-05 16:08:46,618 INFO HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-06-05 16:08:46,742 INFO HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-06-05 16:08:46,751 INFO HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/config.json "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 2639.69it/s]
2026-06-05 16:08:47,072 INFO HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-06-05 16:08:47,204 INFO HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-06-05 16:08:47,329 INFO HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-06-05 16:08:47,454 INFO HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-06-05 16:08:47,576 INFO HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-06-05 16:08:47,585 INFO HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/tokenizer_config.json "HTTP/1.1 200 OK"
2026-06-05 16:08:47,716 INFO HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-06-05 16:08:47,726 INFO HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/config.json "HTTP/1.1 200 OK"
2026-06-05 16:08:47,848 INFO HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-06-05 16:08:47,858 INFO HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/config.json "HTTP/1.1 200 OK"
2026-06-05 16:08:47,983 INFO HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-06-05 16:08:47,993 INFO HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/tokenizer_config.json "HTTP/1.1 200 OK"
2026-06-05 16:08:48,114 INFO HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-06-05 16:08:48,124 INFO HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/tokenizer_config.json "HTTP/1.1 200 OK"
2026-06-05 16:08:48,257 INFO HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-06-05 16:08:48,381 INFO HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-06-05 16:08:50,556 INFO HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2 "HTTP/1.1 200 OK"
2026-06-05 16:08:50,939 INFO HTTP Request: HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-06-05 16:08:50,949 INFO HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/e8f8c211226b894fcb81acc59f3b34ba3efd5f42/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
2026-06-05 16:08:51,077 INFO HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2 "HTTP/1.1 200 OK"
2026-06-05 16:10:31,769 INFO saved 223 rows -> C:\Users\stefa\Downloads\wsa-ferrari-luce\data\processed\topics_keywords.csv
2026-06-05 16:10:31,770 INFO BERTopic found 223 topics.
2026-06-05 16:10:32,485 INFO saved 19680 rows -> C:\Users\stefa\Downloads\wsa-ferrari-luce\data\processed\documents_enriched.csv
2026-06-05 16:10:32,531 INFO saved 3 rows -> C:\Users\stefa\Downloads\wsa-ferrari-luce\data\processed\language_sentiment.csv
2026-06-05 16:10:32,534 INFO Language x sentiment:
lang_group  negative  neutral  positive  total  negative_ratio
        en      8031     6718      2216  16965           0.473
        it        13      394        15    422           0.031
     other       375     1730       188   2293           0.164

           aspects  negative  neutral  positive  total  negative_ratio
0  electrification      3289     3054      1456   7799           0.422
1    exterior_look      2853     1945      1238   6036           0.473
2     design_house      1474     1568       689   3731           0.395
3             name       818     1887       568   3273           0.250
4            price      1338     1077       446   2861           0.468
5      performance       572      707       332   1611           0.355
6         interior       528      527       384   1439           0.367
7   brand_identity       644      561       187   1392           0.463
8            sound       174      162        82    418           0.416

  lang_group  negative  neutral  positive  total  negative_ratio
0         en      8031     6718      2216  16965           0.473
1         it        13      394        15    422           0.031
2      other       375     1730       188   2293           0.164

### 4.4 NER + entity-level sentiment (LAB 6)

In [10]:
from src.ner_entities import main as run_ner
run_ner()
display(pd.read_csv("data/processed/entity_frequency.csv").head(20))
display(pd.read_csv("data/processed/entity_sentiment.csv").head(20))

2026-06-05 16:13:50,463 INFO saved 6553 rows -> C:\Users\stefa\Downloads\wsa-ferrari-luce\data\processed\entity_frequency.csv
2026-06-05 16:13:50,519 INFO saved 2562 rows -> C:\Users\stefa\Downloads\wsa-ferrari-luce\data\processed\entity_cooccurrence.csv
2026-06-05 16:13:50,889 INFO saved 6553 rows -> C:\Users\stefa\Downloads\wsa-ferrari-luce\data\processed\entity_sentiment.csv
2026-06-05 16:13:50,896 INFO Top entities:
      entity   label  count
     ferrari  PERSON   5052
        luce PRODUCT    722
ferrari luce     ORG    507
     chinese    NORP    379
       apple     ORG    352
     porsche     ORG    312
        jony  PERSON    290
    ferraris  PERSON    271
       china     GPE    210
      taycan    NORP    208
       tesla    NORP    197
     italian    NORP    170
       honda     ORG    137
         bmw     ORG    119
         f80     ORG    113

          entity    label  count
0        ferrari   PERSON   5052
1           luce  PRODUCT    722
2   ferrari luce      ORG    507
3        chinese     NORP    379
4          apple      ORG    352
5        porsche      ORG    312
6           jony   PERSON    290
7       ferraris   PERSON    271
8          china      GPE    210
9         taycan     NORP    208
10         tesla     NORP    197
11       italian     NORP    170
12         honda      ORG    137
13           bmw      ORG    119
14           f80      ORG    113
15    ferrari ev      ORG    111
16        toyota      ORG    106
17      mercedes      ORG    102
18       hyundai      ORG     95
19           v12  PRODUCT     87

          entity  total  positive  neutral  negative  negative_ratio
0        ferrari   5829       935     2638      2256           0.387
1           luce    734       168      322       244           0.332
2   ferrari luce    515        66      381        68           0.132
3        chinese    379        38      135       206           0.544
4          apple    353        75      149       129           0.365
5        porsche    312        67      137       108           0.346
6           jony    290        77      125        88           0.303
7       ferraris    280        51      118       111           0.396
8          tesla    211        44       78        89           0.422
9          china    210        22       91        97           0.462
10        taycan    208        63       69        76           0.365
11       italian    170        44       68        58           0.341
12         honda    137        24       61        52           0.380
13           bmw    119        22       47        50           0.420
14           f80    117        34       38        45           0.385
15    ferrari ev    111        18       50        43           0.387
16        toyota    106        14       47        45           0.425
17      mercedes    102        15       46        41           0.402
18       hyundai     95        13       44        38           0.400
19           v12     89        12       41        36           0.404

### 4.5 Visualizations
All charts are saved to `figures/` as PNGs, including the community-coloured interaction network.

In [1]:
from src.viz import main as run_viz
run_viz()
for f in sorted(glob.glob("figures/*.png")):
    print(f); display(Image(f))

2026-06-05 18:14:51,523 INFO figure -> C:\Users\stefa\Downloads\wsa-ferrari-luce\figures\sentiment_distribution.png
2026-06-05 18:14:51,747 INFO figure -> C:\Users\stefa\Downloads\wsa-ferrari-luce\figures\emotions.png
2026-06-05 18:14:51,928 INFO figure -> C:\Users\stefa\Downloads\wsa-ferrari-luce\figures\aspect_sentiment_stacked.png
2026-06-05 18:14:52,014 INFO figure -> C:\Users\stefa\Downloads\wsa-ferrari-luce\figures\aspect_share_pie.png
2026-06-05 18:14:52,331 INFO figure -> C:\Users\stefa\Downloads\wsa-ferrari-luce\figures\sentiment_timeline.png
c:\Users\stefa\Downloads\wsa-ferrari-luce\.venv\Lib\site-packages\sklearn\feature_extraction\text.py:412: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['let'] not in stop_words.
  warnings.warn(
2026-06-05 18:14:53,978 INFO figure -> C:\Users\stefa\Downloads\wsa-ferrari-luce\figures\wordcloud_negative.png
2026-06-05 18:14:54,416 INFO figure -> C:\Users\stefa\Downloads\wsa-ferrari-luce\figures\wordcloud_neutral.png
2026-06-05 18:14:54,817 INFO figure -> C:\Users\stefa\Downloads\wsa-ferrari-luce\figures\wordcloud_positive.png
2026-06-05 18:14:54,994 INFO figure -> C:\Users\stefa\Downloads\wsa-ferrari-luce\figures\centrality_top.png
2026-06-05 18:14:55,163 INFO figure -> C:\Users\stefa\Downloads\wsa-ferrari-luce\figures\entity_frequency.png
2026-06-05 18:14:56,139 INFO figure -> C:\Users\stefa\Downloads\wsa-ferrari-luce\figures\community_network.png

NameError: name 'glob' is not defined

### 4.6 Download everything
One Colab run produces the complete result set from the bundled data. This packs all
tables (`data/processed/`) and charts (`figures/`, including the interactive
`community_network.html`) into a single zip and downloads it — so you leave with everything.

In [ ]:
import os, zipfile
ZIP = "WSA_FerrariLuce_results.zip"
with zipfile.ZipFile(ZIP, "w", zipfile.ZIP_DEFLATED) as z:
    for root in ("data/processed", "figures"):
        for dp, _, files in os.walk(root):
            for f in files:
                if f == ".gitkeep":
                    continue
                z.write(os.path.join(dp, f))
print(f"bundled all results -> {ZIP} ({os.path.getsize(ZIP) // 1024} KB)")

# On Colab this triggers a browser download of the full bundle.
try:
    from google.colab import files
    files.download(ZIP)
except Exception:
    print("(not on Colab — grab the zip from the file browser on the left)")
    #trying

# Optional: copy everything to Google Drive instead of downloading.
# from google.colab import drive; drive.mount("/content/drive")
# !mkdir -p "/content/drive/MyDrive/WSA_FerrariLuce" && cp -r data figures "/content/drive/MyDrive/WSA_FerrariLuce/"

bundled all results -> WSA_FerrariLuce_results.zip (8985 KB)
(not on Colab — grab the zip from the file browser on the left)